# Generated by Django 4.1.3 on 2023-01-16 15:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-publish_date'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data publikacji'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='cat', unique=True, verbose_name='category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=230),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='tytul', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug', 'parent')},
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
    ]
