# Generated by Django 4.1.3 on 2022-12-20 12:06

from django.db import migrations, models
import store.models.customer


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/avatar.png', max_length=255, upload_to=store.models.customer.Customer.image_upload_to),
        ),
    ]
