# Generated by Django 4.1.3 on 2023-01-17 14:40

import dictionary.models.article
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0003_alter_category_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(max_length=250)),
                ('content', tinymce.models.HTMLField(blank=True, default='')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data publikacji')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data modyfikacji')),
                ('image', models.ImageField(default='default/no_image.jpg', max_length=255, upload_to=dictionary.models.article.Article.image_upload_to)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='store.category', verbose_name='category')),
            ],
            options={
                'verbose_name_plural': 'articles',
                'ordering': ['-publish_date'],
            },
        ),
    ]
