# Generated by Django 4.1.3 on 2023-01-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='a', unique=True, verbose_name='article'),
            preserve_default=False,
        ),
    ]
